<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="APL-LHR-JA0201" failures="1" tests="1" name="Default test" time="715.707" errors="0" timestamp="2022-09-23T13:06:01 PKT">
  <testcase classname="Test.Ancera.MetaData.DataUpload" name="FlockMetadata" time="663.825">
    <failure type="java.lang.Exception" message="java.lang.AssertionError: The following asserts failed:
	expected [Flock Metadata.xlsx loaded successfully.] but found [An error occurred (E129). Please contact support at support@ancera.com or 203-871-3756]">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: The following asserts failed:
expected [Flock Metadata.xlsx loaded successfully.] but found [An error occurred (E129). Please contact support at support@ancera.com or 203-871-3756]
at Test.Ancera.MetaData.DataUpload.FlockMetadata(DataUpload.java:134)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: The following asserts failed:
expected [Flock Metadata.xlsx loaded successfully.] but found [An error occurred (E129). Please contact support at support@ancera.com or 203-871-3756]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Test.Ancera.MetaData.DataUpload.FlockMetadata(DataUpload.java:125)
... 28 more
]]>
    </failure>
  </testcase> <!-- FlockMetadata -->
  <testcase classname="Test.Ancera.MetaData.DataUpload" name="SampleMetaData" time="0.0">
    <ignored/>
  </testcase> <!-- SampleMetaData -->
  <testcase classname="Test.Ancera.MetaData.DataUpload" name="saveTemplates" time="0.0">
    <ignored/>
  </testcase> <!-- saveTemplates -->
  <testcase classname="Test.Ancera.MetaData.DataUpload" name="SitePerformance" time="0.0">
    <ignored/>
  </testcase> <!-- SitePerformance -->
</testsuite> <!-- Default test -->
