<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K0SFL7M" failures="0" tests="15" name="Test.Ancera.MetaData.DataTemplateManagement" time="262.050" errors="1" timestamp="2022-06-19T15:29:36 PKT" skipped="0">
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="Navigate" time="9.483"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="ResetFieldCheck" time="7.745"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="ClmResetFieldCheck" time="4.724"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="MandatoryFieldCheck" time="39.218"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="CreateTemplate" time="26.713"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="UpdateTemplateColumn" time="8.715"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="DeleteColumnTemplate" time="2.826"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="UpdateTemplate" time="12.909"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="ExportTemplate" time="10.954"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="IdentificationColumnTest" time="20.842"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="InActivateTemplate" time="23.177"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="DeleteTemplate" time="31.052"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="VerifyClientMappingPopup" time="10.594"/>
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="VerifyClientMappingList" time="39.403">
    <error message="java.lang.AssertionError: The following asserts failed:
	expected [4] but found [-1]" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: The following asserts failed:
expected [4] but found [-1]
at Test.Ancera.MetaData.DataTemplateManagement.VerifyClientMappingList(DataTemplateManagement.java:1011)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: The following asserts failed:
expected [4] but found [-1]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Test.Ancera.MetaData.DataTemplateManagement.VerifyClientMappingList(DataTemplateManagement.java:1003)
... 28 more
]]>
    </error>
  </testcase> <!-- VerifyClientMappingList -->
  <system-out/>
  <testcase classname="Test.Ancera.MetaData.DataTemplateManagement" name="VerifyClientUploadScreen" time="13.695"/>
  <system-out/>
</testsuite> <!-- Test.Ancera.MetaData.DataTemplateManagement -->
