<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="LAPTOP-O6K4VQH7" name="Test.Ancera.Reports.ExternalCoccidia" tests="13" failures="0" timestamp="2021-02-01T17:48:38 PKT" time="872.213" errors="2">
  <testcase name="NavigateCoccidia" time="52.727" classname="Test.Ancera.Reports.ExternalCoccidia"/>
  <system-out/>
  <testcase name="DateFilter" time="108.687" classname="Test.Ancera.Reports.ExternalCoccidia"/>
  <system-out/>
  <testcase name="EnterDate" time="45.308" classname="Test.Ancera.Reports.ExternalCoccidia"/>
  <system-out/>
  <testcase name="DateLockFilter" time="20.707" classname="Test.Ancera.Reports.ExternalCoccidia"/>
  <system-out/>
  <testcase name="TestFilters" time="455.582" classname="Test.Ancera.Reports.ExternalCoccidia"/>
  <system-out/>
  <testcase name="ResetFilter" time="20.913" classname="Test.Ancera.Reports.ExternalCoccidia"/>
  <system-out/>
  <testcase name="CoccidiaLock" time="22.892" classname="Test.Ancera.Reports.ExternalCoccidia"/>
  <system-out/>
  <testcase name="Pagination" time="49.282" classname="Test.Ancera.Reports.ExternalCoccidia"/>
  <system-out/>
  <testcase name="RowsPerPage" time="75.921" classname="Test.Ancera.Reports.ExternalCoccidia"/>
  <system-out/>
  <testcase name="PNGExport" time="9.544" classname="Test.Ancera.Reports.ExternalCoccidia">
    <error type="java.lang.Exception" message="java.lang.AssertionError: expected [true] but found [false]">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: expected [true] but found [false]
at Test.Ancera.Reports.ExternalCoccidia.PNGExport(ExternalCoccidia.java:1454)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Test.Ancera.Reports.ExternalCoccidia.PNGExport(ExternalCoccidia.java:1445)
... 28 more
]]>
    </error>
  </testcase> <!-- PNGExport -->
  <system-out/>
  <testcase name="CSVExport" time="5.627" classname="Test.Ancera.Reports.ExternalCoccidia">
    <error type="java.lang.Exception" message="java.lang.AssertionError: expected [true] but found [false]">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: expected [true] but found [false]
at Test.Ancera.Reports.ExternalCoccidia.CSVExport(ExternalCoccidia.java:1513)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Test.Ancera.Reports.ExternalCoccidia.CSVExport(ExternalCoccidia.java:1504)
... 28 more
]]>
    </error>
  </testcase> <!-- CSVExport -->
  <system-out/>
  <testcase name="TemplateExport" time="5.023" classname="Test.Ancera.Reports.ExternalCoccidia"/>
  <system-out/>
  <testcase name="RunAPI" classname="Test.Ancera.Reports.ExternalCoccidia">
    <skipped/>
  </testcase> <!-- RunAPI -->
  <system-out/>
</testsuite> <!-- Test.Ancera.Reports.ExternalCoccidia -->
