<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K0SFL7M" failures="0" tests="11" name="Test.Ancera.Reports.Sites_Log" time="694.828" errors="2" timestamp="2022-07-26T11:40:05 PKT" skipped="0">
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="NavigateSites" time="7.418"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="TestFilter" time="155.647"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="wildcard" time="219.600"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="SitesLock" time="146.552"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="Pagination" time="3.997"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="RowsPerPage" time="4.493"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="Sorting" time="0.734"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="AllignmentTest" time="0.326"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="FieldAccess" time="132.932"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="CSVExport" time="13.468">
    <error message="java.lang.AssertionError: The following asserts failed:
	expected [04/26/2021] but found [04-26-2021]" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: The following asserts failed:
expected [04/26/2021] but found [04-26-2021]
at Test.Ancera.Reports.Sites_Log.CSVExport(Sites_Log.java:1046)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: The following asserts failed:
expected [04/26/2021] but found [04-26-2021]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Test.Ancera.Reports.Sites_Log.CSVExport(Sites_Log.java:1041)
... 28 more
]]>
    </error>
  </testcase> <!-- CSVExport -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.Sites_Log" name="CSVAuditExport" time="9.661">
    <error message="java.lang.AssertionError: expected [Sites Audit Log - 20220726_1140.csv] but found [Sites Audit Log - 20220726_1139.csv]" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: expected [Sites Audit Log - 20220726_1140.csv] but found [Sites Audit Log - 20220726_1139.csv]
at Test.Ancera.Reports.Sites_Log.CSVAuditExport(Sites_Log.java:1109)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [Sites Audit Log - 20220726_1140.csv] but found [Sites Audit Log - 20220726_1139.csv]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Test.Ancera.Reports.Sites_Log.CSVAuditExport(Sites_Log.java:1097)
... 28 more
]]>
    </error>
  </testcase> <!-- CSVAuditExport -->
  <system-out/>
</testsuite> <!-- Test.Ancera.Reports.Sites_Log -->
